describe('Test a Keypad component', () => {
  it('It is should be with all keycups on keypad', () => {
    cy.visit('/')

    cy.get('[data-test-target="keypad-element-with-keycup-C"]').should(
      'have.text',
      'C'
    )
    cy.get('[data-test-target="keypad-element-with-keycup--"]').should(
      'have.text',
      '-'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-+"]').should(
      'have.text',
      '+'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-."]').should(
      'have.text',
      '.'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-*"]').should(
      'have.text',
      '*'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-/"]').should(
      'have.text',
      '/'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-="]').should(
      'have.text',
      '='
    )
    cy.get('[data-test-target="keypad-element-with-keycup-CE"]').should(
      'have.text',
      'CE'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-1"]').should(
      'have.text',
      '1'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-2"]').should(
      'have.text',
      '2'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-3"]').should(
      'have.text',
      '3'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-4"]').should(
      'have.text',
      '4'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-5"]').should(
      'have.text',
      '5'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-6"]').should(
      'have.text',
      '6'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-7"]').should(
      'have.text',
      '7'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-8"]').should(
      'have.text',
      '8'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-9"]').should(
      'have.text',
      '9'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-0"]').should(
      'have.text',
      '0'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-("]').should(
      'have.text',
      '('
    )
    cy.get('[data-test-target="keypad-element-with-keycup-)"]').should(
      'have.text',
      ')'
    )
  })
  it('All buttons should be clickable and displays on the expression, if this buttons are operation like "=", "C", "CE then are not displays like a symbols"', () => {
    cy.visit('/')

    cy.get('[data-test-target="keypad-element-with-keycup-1"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup--"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-2"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-+"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-("]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-3"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-/"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-4"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-*"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-5"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-."]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-6"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-7"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-8"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-9"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-0"]').click()
    cy.get('[data-test-target="display-expression"]').should(
      'have.text',
      '1-2+(3/4*5.67890'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-CE"]').click()
    cy.get('[data-test-target="display-expression"]').should(
      'have.text',
      '1-2+(3/4*5.6789'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-)"]').click()
    cy.get('[data-test-target="keypad-element-with-keycup-="]').click()
    cy.get('[data-test-target="display-expression"]').should(
      'have.text',
      '1-2+(3/4*5.6789) = 3.259'
    )
    cy.get('[data-test-target="keypad-element-with-keycup-C"]').click()
    cy.get('[data-test-target="display-expression"]').should('have.text', '0')
  })
})
